artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://drive.google.com/file/d/1c_WJe0N-Fauwh6SkGxGrCFYhMIYQ32Y_/view?usp=sharing
    local_data_file: artifacts/data_ingestion/EmotionImages.zip
    unzip_dir: artifacts/data_ingestion


